version: "3.7"

services:
    # image project
    app:
        container_name: elearning_laravel_9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-9-network
    
    # nginx
    nginx:
        container_name: elearning_nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9-network

    # db postgres
    postgresql:
        container_name: elearning_postgres
        image: postgres
        restart: unless-stopped
        environment: 
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/postgresql/dbdata:/var/lib/postgresql
        ports: 
            - "5433:5432"
        networks: 
            - laravel-9-network

    # queue
    queue:
        container_name: elearning_queue
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel-9-network

    # redis
    redis:
        container_name: elearning_redis
        image: redis:latest
        networks: 
            - laravel-9-network

networks: 
    laravel-9-network:
        driver: bridge